name: Continuous Integration with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21.0.9'
        distribution: 'temurin'
        cache: maven

    - name: Build & Test with Coverage
      run: mvn clean verify jacoco:report

    - name: Submit coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: mvn coveralls:report
