name: Continuous integration with Maven

on: 
	push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.412+8'
        distribution: 'temurin'
        cache: maven
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.6
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test with JaCoCo
      run: mvn test jacoco:report
    - name: Report to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
      run: mvn coveralls:report
      